/* eslint-disable no-empty-function, no-unused-vars */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* LIB_DEFINITION{
  "name": "LIB_PR_CUSTOMIZATION_SERVER_SAMPLE",
  "libraryType": "Lib",
  "scriptType": "SERVER",
  "comment": "Custom library extending Purchase Requisition scripts on server side",
  "versionable": false,
  "require": [
    "Sys/Sys",
    "Sys/Sys_RecognitionEngine_Parameters"
  ]
}*/
/**
 * @namespace Lib.PR.Customization.Server
 * @description Package Purchase Requisition server script customization callbacks
 */
var Lib;
(function (Lib) {
    var PR;
    (function (PR) {
        var Customization;
        (function (Customization) {
            var Server;
            (function (Server) {
                /**
                 * @method Lib.PR.Customization.Server.OnExtractionScriptEnd
                 * @description Allows you to customize the value of the fields available on the purchase requisition form.
                 * 		This user exit is called at the end of the extraction script of the Purchase Requisition process.
                 *		For example, you can fill in the purchase requisition with values coming from an XML file. This XML file
                 *		containing the data of a purchase requisition may have been generated by another tool (ERP, etc.).
                 *		After the extraction script, the purchase requisition can follow the usual approval workflow.
                 * @since 143
                 * @example
                 * 	OnExtractionScriptEnd: function ()
                 * 	{
                 * 		// Sets the default currency
                 * 	 	Data.SetValue("Currency__", "USD");
                 * 	}
                 */
                Server.OnExtractionScriptEnd = function () {
                };
                /**
                 * @method Lib.PR.Customization.Server.IsAutoCreateOrderEnabled
                 * @description Allows you to automate the purchase order creation under the conditions of your choice.
                 * 		This user exit is called in the validation script of the Purchase Requisition process.
                 * @since 110
                 * @returns {boolean} true: the order is automatically created, false the order is not automatically created
                 * @example
                 * 	IsAutoCreateOrderEnabled: function ()
                 * 	{
                 *		var itemsTable = Data.GetTable("LineItems__");
                 *		var firstItem = itemsTable.GetItem(0);
                 *		var firstItemVendorNumber, areSameVendors = true;
                 *		if (firstItem)
                 *		{
                 *			firstItemVendorNumber = firstItem.GetValue("VendorNumber__");
                 *		}
                 *		for (var i = itemsTable.GetItemCount() - 1; i > 0; i--)
                 *		{
                 *			var currentItemVendorNumber = itemsTable.GetItem(i).GetValue("VendorNumber__");
                 *			areSameVendors = areSameVendors && (currentItemVendorNumber === firstItemVendorNumber);
                 *		}
                 *
                 *		var totalNetAmount = Data.GetValue("TotalNetAmount__");
                 *
                 *		Log.Info("Auto Create PO - First item vendor number = ", firstItemVendorNumber);
                 *		Log.Info("Auto Create PO - Identical vendors on all lines = ", areSameVendors);
                 *		Log.Info("Auto Create PO - Total net amount = " + totalNetAmount);
                 *
                 *		var isCorrectVendor = firstItemVendorNumber === "01254796";
                 *		autoCreateOrder = areSameVendors && isCorrectVendor && totalNetAmount < 100;
                 *
                 *		Log.Info("Auto Create PO - is set to: ", autoCreateOrder);
                 *		return autoCreateOrder;
                 * 	}
                 */
                Server.IsAutoCreateOrderEnabled = function () {
                    return false;
                };
                /**
                 * @method Lib.PR.Customization.Server.OnBilling
                 * @description Allows you to override the user whose contract is used to bill the process.
                 * 		By default, the user who is the owner of the process at the process creation is the user whose contract is billed. If the owner is a group of users, the billed contract is the contract of the user who eventually validates the process.
                 * 		For versions 5.132 or higher of the Purchasing or Purchase to Pay application, the purchase requisition is billed when the requester submits it. The processingLabel variable for a purchase requisition is PA002 and must not be changed.
                 * 		For version 5.131 or lower of the Purchasing application, the purchase requisition is billed when all the goods have been received.
                 * 		For version 5.134 or higher of the Purchasing or Purchase to Payapplication, the archive is billed at the same time as the purchase requisition.
                 * @since 132
                 * @returns {boolean} Boolean value specifying whether the billing information has correctly been set:
                 *		true: The billing information is correct and the process can be approved.
                 *		false: The billing information is not correct and the process cannot be approved.
                 * @example
                 * 	OnBilling: function ()
                 * 	{
                 *		var info = { userId: "john@example.com" };
                 *		Log.Info("Set billing info: " + info.userId);
                 *		if (!Process.SetBillingInfo(info))
                 *		{
                 *			Log.Error("Error setting billing info: " + info.userId);
                 *			Process.PreventApproval();
                 *			return false;
                 *		}
                 *		return true;
                 * 	}
                 */
                Server.OnBilling = function () {
                    return true;
                };
                /**
                 * @method Lib.PR.Customization.Server.OnSendEmailNotification
                 * @description Allows you to modify the email notifications. This user exit is called before the notification is sent.
                 * @since 134
                 * @param {Sys.EmailNotification.SendEmailNotificationWithUserIdOptions} emailOptions JavaScript object specifying the email options
                 * @param {string} emailOptions.userId Identifier of the user who should receive the email notification.
                 * @param {string} emailOptions.subject	Subject of the email notification.
                 * @param {string} emailOptions.template Template used for the email notification.
                 * @param {string} emailOptions.fromName Name of the email sender.
                 * @param {boolean} emailOptions.backupUserAsCC Specifies if the email address of the delegate user should be added in the Cc field of the email notification:
                 *		true : the notification is sent.
                 *		false: the notification is not sent.
                 * @returns {boolean} Boolean value specifying whether the notification should be sent:
                 *		true: The email notification should be sent.
                 *		false: The email notification should not be sent.
                 * @example
                 * 	OnSendEmailNotification: function (emailOptions)
                 * {
                 *	 // The current email notification is the notification sent to the requester
                 *	 // to inform him that his purchase requisition has been rejected.
                 *	 if (emailOptions.subject === "_A purchase requisition has been rejected")
                 *	 {
                 *		 var workflow = Sys.WorkflowController.Create({ version: 1 });
                 *		 var options = {
                 *			 userId: workflow.GetContributorAt(1).login, // The recipient is the first approver.
                 *			 subject: emailOptions.subject,
                 *			 template: emailOptions.template,
                 *			 fromName: "Esker Purchase requisition",
                 *			 backupUserAsCC: emailOptions.backupUserAsCC
                 *		 };
                 *		 Lib.EmailNotification.SendEmailNotification(options);
                 *	 }
                 *	 return true;
                 * }
                 *
                 */
                Server.OnSendEmailNotification = function (emailOptions) {
                    return true;
                };
                /**
                 * @method Lib.PR.Customization.Server.OnVendorRecognition
                 * @description Allows you to define additional information on the purchase requisition according to the recognized vendor.
                 * 		This user exit is called in the extraction script of the Purchase Requisition process, when a quotation has been uploaded and when a vendor has been recognized.
                 * @since 133
                 * @param {ESKMap<string>} result An ESKMap<string> object representing a record of the vendor table.
                 * 		Use the result.xxx with the fields of the AP - Vendors__ table to retrieve the vendor properties.
                 * @example
                 *	OnVendorRecognition: function (vendorRecord)
                 *	{
                 *		// This user exit updates the currency of the purchase requisition with the currency of the vendor recognized on the quotation:
                 *		Log.Info("Vendor recognized, currency= " + vendorRecord.Currency__);
                 *		Data.SetValue("Currency__", vendorRecord.Currency__);
                 *	}
                 */
                Server.OnVendorRecognition = function (result) {
                };
                /**
                 * @method Lib.PR.Customization.Server.OnUnknownAction
                 * @description Allows you to customize how the action is processed when the validation script executes an unknown action.
                 *		This user exit is called when the validation script of the Purchase Requisition process is triggered by an unknown action.
                 * @since 148
                 * @param {string} currentAction value specifying the type of action that triggered the execution of the script.
                 * 		This value is retrieved using the Processing scripts API: Data.GetActionType function.
                 * @param {string} currentName value specifying the name of the action that triggered the execution of the script.
                 * 		This value is retrieved using the Processing scripts API: Data.GetActionName function.
                 * @returns {boolean} Boolean value indicating whether the action has been handled. Possible values are:
                 * 		true: The action has been handled.
                 * 		false: The action has not been handled.
                 * @example
                 * 	OnUnknownAction: function (currentAction, currentName)
                 *	{
                 *		// This user exit logs the unknown actions details.
                 *		Log.Error(currentAction + "-" + currentName);
                 *	}
                 * }
                 */
                Server.OnUnknownAction = function (currentAction, currentName) {
                    return false;
                };
                /**
                 * @method Lib.PR.Customization.Server.OnValidationScriptEnd
                 * @description Allows you to perform operations after the Purchase Requisition process validation.
                 * 		This user exit is called at the end of the validation script of the Purchase Requisition process.
                 * @since 149
                 * @param {string} currentAction value specifying the type of action that triggered the execution of the script.
                 * 		This value is retrieved using the Processing scripts API: Data.GetActionType function.
                 * @param {string} currentName value specifying the name of the action that triggered the execution of the script.
                 * 		This value is retrieved using the Processing scripts API: Data.GetActionName function.
                 * @param {boolean} isRecallScriptScheduled value indicating if the user exit is expected to be called again in the current workflow step.
                 * 		The validation script contains calls to the RecallScript function, thus the validation script is called several times at each workflow step.
                 * 		This parameter is set to false after the last execution of the RecallScript function.
                 * @param {boolean} isFormInError value indicating whether the form is currently in an error state, only available since S346.
                 * 		This parameter allows you to know if there are validation errors on the form when the user exit is executed.
                 * @example In the following example, a user is allowed to read the Purchase Requisition.
                 *	OnValidationScriptEnd: function (currentAction, currentName, isRecallScriptScheduled, isFormInError)
                 *	{
                 *	 	Process.AddRight("john.more@example.com", "read")
                 *	}
                 */
                Server.OnValidationScriptEnd = function (currentAction, currentName, isRecallScriptScheduled, isFormInError) {
                };
                /**
                 * @method Lib.PR.Customization.Server.GetNumber
                 * @description Allows you to retrieve the next document number based on a customized numbering sequence. This user exit is called in the validation script of the Purchase Requisition, Purchase Order or Goods Receipt process, depending on the library in which it is located.
                 * @since 110
                 * @param {string} defaultSequenceName String value representing the name of the sequence that is retrieved by default, when this user exit is not implemented. To keep on using the default numbering, use it as is to retrieve numbers from the default sequence.
                 * @returns {string} String value containing the next number from your customized sequence.
                 * @example
                 * For example, when using the US01 and FR01 company codes with the above script, you could get the following numbering: US01-0001, US01-0002, US01-0003, FR01-0001, US01-0004, FR01-0002, etc.
                 * 	Server.GetNumber = function (defaultSequenceName)
                 * 	{
                 * 		var number = "";
                 * 		var ReqNumberSequence = Process.GetSequence(defaultSequenceName);
                 * 		number = ReqNumberSequence.GetNextValue();
                 * 		if (number === "")
                 * 		{
                 * 			Log.Info("Error while retrieving a number");
                 * 		}
                 * 		else
                 * 		{
                 * 			Log.Info("Number:" + number);
                 * 		}
                 * 		return number;
                 *	};
                 */
                /*
                export const GetNumber = function (defaultSequenceName: string): string
                {
                    // Must return something
                };
                */
                /**
                 * @method Lib.PR.Customization.Server.GetListOfExtraUsersWithReadRight
                 * @description Allow you to return a list of user to give read right to.
                 * @since 288
                 * @returns {Array<string>} array of login to give read rights to
                 * @example
                 * For exemple, always add read rights to big.boss@company.com.
                 * 	GetListOfExtraUsersWithReadRight: function ()
                 * 	{
                 * 		var costCenters = [];
                 * 		var lineItems = Data.GetTable("LineItems__");
                 * 		var nbItems = lineItems.GetItemCount();
                 * 		for (var i = 0; i < nbItems; i++)
                 * 		{
                 * 			var item = lineItems.GetItem(i);
                 * 			var cc = item.GetValue("ItemCostCenterId__");
                 * 			if (cc && costCenters.indexOf(cc) < 0)
                 * 			{
                 * 				costCenters.push(cc);
                 * 			}
                 * 		}
                 * 		var list = [];
                 * 		if (costCenters.length > 0)
                 * 		{
                 * 			var filter = Sys.Helpers.LdapUtil.FilterAnd(
                 * 				"(" + Lib.P2P.GetCompanyCodeFilter(Data.GetValue("CompanyCode__")) + ")",
                 * 				Sys.Helpers.LdapUtil.FilterIn("CostCenter__", costCenters)
                 * 			).toString();
                 * 			Sys.GenericAPI.Query("AP - Cost centers__", filter, ["Manager__"], function (result, error)
                 * 			{
                 * 				if (error || !result)
                 * 				{
                 * 					return;
                 * 				}
                 * 				for (var i = 0; i < result.length; i++)
                 * 				{
                 * 					var r = result[i];
                 * 					if (r.Manager__ && list.indexOf(r.Manager__) === -1)
                 * 					{
                 * 						list.push(r.Manager__);
                 * 					}
                 * 				}
                 * 			}, null, -1, { useConstantQueryCache: true });
                 * 		}
                 * 		return list;
                 * 	}
                 */
                Server.GetListOfExtraUsersWithReadRight = function () {
                    return [];
                };
                /**
                 * @method Lib.PR.Customization.Server.OnValidationScriptBegin
                 * @description Allows you to perform operations at the beginning of the validation script of the Purchase Requisition process.
                 * 				This user exit is called at the beginning of the validation script of the Purchase Requisition process.
                 * 				Be aware that this UE is called at the beginning of the validation script, therefore some data may be edited later in the script.
                 * @since 332
                 * @param {string} currentName String value specifying the name of the action that triggered the execution of the script.
                 * 		This value is retrieved using the Processing scripts API: Data.GetActionName function.
                 * @param {string} currentAction String value specifying the type of action that triggered the execution of the script.
                 * 		This value is retrieved using the Processing scripts API: Data.GetActionType function.
                 * @example In the following example, we call SetAllowTableValuesOnly on a custom field after submitting the PR.
                 * 	OnValidationScriptBegin: function (currentName, currentAction)
                 * 	{
                 * 		Data.SetAllowTableValuesOnly("Z_YourCustomField__", false);
                 * 	}
                 */
                Server.OnValidationScriptBegin = function (currentName, currentAction) {
                };
            })(Server = Customization.Server || (Customization.Server = {}));
        })(Customization = PR.Customization || (PR.Customization = {}));
    })(PR = Lib.PR || (Lib.PR = {}));
})(Lib || (Lib = {}));
//# sourceMappingURL=LIB_PR_CUSTOMIZATION_SERVER_SAMPLE.js.map