/* LIB_DEFINITION{
  "name": "LIB_DD_CUSTOMIZATION_COMMON_SAMPLE",
  "libraryType": "Lib",
  "scriptType": "COMMON",
  "comment": "PS configurations that can be used in all scripts",
  "versionable": false,
  "require": []
}*/

/**
 * Package DD common user exits
 * @namespace Lib.DD.Customization.Common
 */

var Lib = Lib || {};
Lib.DD = Lib.DD || {};
Lib.DD.Customization = Lib.DD.Customization || {};

Lib.DD.Customization.Common = (function ()
{
	/**
	 * @lends Lib.DD.Customization.Common
	 */
	var Common =
	{
		/**
		 * This function is called to set unique client ID for AI model.
		 * This function can be used to separate AI model for DEV/QA/PROD environment in the same account, or any other criteria.
		 * Be aware to only use lowercase alphanumeric character for unique ID except if using ACS classifier.
		 * Main account ID is concatenated to the client ID returned by this function.
		 * If it returns an empty string, only one model will exist for this client because we will only use the main account id.
		 * The exception for this is with the Azure Cognitive Services. We always use the main account id and sub account id to isolate models, to whom we concatenate the client Id.
		 * @return {string} Unique client ID
		 * @example
		 * <pre><code>
		 *	SetClientId: function () {
		 *		return "dev";
		 * }
		 * </code></pre>
		 */
		SetClientId: function ()
		{
			return "";
		},

		CustomizeSalesforceObjectInfo: function (info)
		{
			return info;
		},

		/**
		 * This function is called when the "Enable replies generated by ChatGPT" option is enabled for the current document type.
		 * This function may be called either from the extraction script or the HTML page script.
		 * This function is used to customize the standard functions used by ChatGPT to generate a reply to the customer.
		 * This function may modify the function array argument.
		 * Each function in the function array can be implemented in 3 ways:
		 * 1) Synchronous implementation: the function returns a JavaScript value.
		 * 2) Asynchronous implementation using Promises: the function retruns a Promise that resolves to a JavaScript value.
		 * 3) Asynchronous implementation using a callback: the function calls the callback available through the "this" keyword with a JavaScript value as argument and returns undefined.
		 * Notes:
		 * The function name and the argument names must be understandable by ChatGPT.
		 * A JavaScript comment after the funtion signature might help ChatGPT.
		 * @param {string} functions - array of standard functions
		 * @param {object} options - Optional dictionary of options, including the "context" key that contains the context in which the functions are requested.
		 * @example
		 * <pre><code>
		 * OnGptPluginsFunctions: function (functions, options)
		 * {
		 * 		// add a function to the standard functions
		 * 		functions.push(function GetProductDescription(productNumber)
		 * 		{
		 * 			const callback = this;
		 * 			const filter = Sys.Helpers.LdapUtil.FilterEqual("Number__", productNumber).toString();
		 * 			const attributes = ["Number__", "Description__"];
		 * 			Sys.GenericAPI.Query("SO - Materials__", filter, attributes, callback, null, "NO_LIMIT");
		 * 		});
		 * }
		 * </code></pre>
		 * @example
		 * <pre><code>
		 * OnGptPluginsFunctions: function (functions, options)
		 * {
		 * 		// remove a function from the standard functions that we don't want
		 * 		for (var index = 0; index < functions.length; index++)
		 * 		{
		 * 			var item = functions[index];
		 * 			if (item && item.name === "GetProductDescription")
		 * 			{
		 * 				functions[index] = null;
		 * 			}
		 * 		}
		 * }
		 * </code></pre>
		 * @example
		 * <pre><code>
		 * OnGptPluginsFunctions: function (functions, options)
		 * {
		 *  	// override the standard functions or add functions
		 * 		functions.push(function GetProductDescription(productNumber)
		 * 		{
		 * 			// Asynchronous implementation using a callback
		 * 			const callback = this;
		 * 			const filter = Sys.Helpers.LdapUtil.FilterEqual("Number__", productNumber).toString();
		 * 			const attributes = ["Number__", "Description__"];
		 * 			Sys.GenericAPI.Query("SO - Materials__", filter, attributes, callback, null, "NO_LIMIT");
		 * 		});
		 * 		functions.push(function GetProductEAN(productNumber)
		 * 		{
		 * 			// Asynchronous implementation using a Promise
		 * 			return new Promise(resolve => {
		 * 				const filter = Sys.Helpers.LdapUtil.FilterEqual("Number__", productNumber).toString();
		 * 				const attributes = ["Number__", "EAN__"];
		 * 				Sys.GenericAPI.Query("SO - Materials__", filter, attributes, resolve, null, "NO_LIMIT");
		 * 			});
		 * 		});
		 * 		functions.push(function GetDocumentType()
		 * 		{
		 * 			// Synchronous implementation
		 * 			return Data.GetValue("DocumentType__");
		 * 		});
		 * }
		 * </code></pre>
		 * @example
		 * <pre><code>
		 * OnGptPluginsFunctions: function (functions, options)
		 * {
		 * 		// function with a comment
		 * 		function GetProductCharacteristics(productDescription) // retrieve characteristics of a product given it's description
		 * 		{
		 * 			...
		 * 		}
		 * 		functions.push(GetProductCharacteristics);
		 * }
		 * </code></pre>
		 * @example Add a function to the standard functions to create a quote, only in the context of the digital assistant
		 * <pre><code>OnGptPluginsFunctions: function (functions, options) {
		 *    if (options && options.context === "DigitalAssistant") {
		 *       functions.push(function createQuote(product, quantity) {
		 * 	        // Logic to create a quote for current customer
		 *          ...
		 *       });
		 *    }
		 * }</code></pre>
		 */
		OnGptPluginsFunctions: function (functions, options)
		{
			//
		},

		/**
		 * This function is called when the "Enable replies generated by ChatGPT" option is enabled for the current document type.
		 * This function may be called either from the extraction script or the HTML page script.
		 * This function is used to customize the standard function descriptions used by ChatGPT to generate a reply to the customer.
		 * This function may modify the functionsDescription array argument.
		 * Each function description in the functionsDescription array must follow the JSON schema defined in the ChatGPT documentation.
		 * See more information at https://json-schema.org/specification
		 * @param {string} functionsDescription - array of standard functions descriptions
		 * @param {object} options - Optional dictionary of options, including the "context" key that contains the context in which the function descriptions are requested
		 * @returns {void}
		 *
		 * @example Add a function description to the standard functions to get the delivery date for a customer's order
		 * <pre><code>OnGptPluginsFunctionsDescription: function (functionsDescription, options) {
		 *    functionsDescription.push({
		 *     "name": "getDeliveryDate",
		 *     "description": "Get the delivery date for a customer's order. Call this whenever you need to know the delivery date, for example when a customer asks 'Where is my package'",
		 *     "parameters": {
		 *         "type": "object",
		 *         "properties": {
		 *             "orderId": {
		 *                 "type": "string",
		 *                 "description": "The customer's order ID.",
		 *             },
		 *         },
		 *         "required": ["orderId"]
		 *     }
		 * });
		 * }</code></pre>
		 *
		 * @example Add a function description to the standard functions to create a quote, only in the context of the digital assistant
		 * <pre><code>OnGptPluginsFunctionsDescription: function (functionsDescription, options) {
		 *    if (options && options.context === "DigitalAssistant") {
		 * 	     functionsDescription.push({
		 *          "name": "createQuote",
		 *          "description": "Create a quote for a customer. Call this whenever you need to create a quote for a customer, for example when a customer asks 'How much does it cost?'",
		 *          "parameters": {
		 * 	        "type": "object",
		 * 	           "properties": {
		 * 		          "product": {
		 * 			         "type": "string",
		 * 			         "description": "The product for which the quote is created.",
		 * 		          },
		 * 		          "quantity": {
		 * 			         "type": "number",
		 * 			         "description": "The quantity of the product.",
		 * 		          },
		 * 	           },
		 * 	           "required": ["product", "quantity"]
		 *          }
		 *       });
		 *    }
		 * }</code></pre>
		 **/
		OnGptPluginsFunctionsDescription: function (functionsDescription, options)
		{
			//
		},

		/**
		 * This function is called when the "Enable replies generated by ChatGPT" option is enabled for the current document type.
		 * This function may be called either from the extraction script or the HTML page script.
		 * This function is used to customize the standard options used by ChatGPT to generate a reply to the customer.
		 * Available options are:
		 * persona: define the role of the ai, for example: 'Customer Service Representative'
		 * from: define who is sending a message, for example: 'a customer' or 'John'
		 * signature: define the signature to use when writting the answer, if empty o signature specified
		 * culture: define the culture to use to format numbers and dates
		 * temperature: define the temparature to use when generating answers, between 0 and 1, higher values makes the reponses more creative.
		 * additionalInformation: any additionnal information to give to chat gpt to generate answers;
		 * @param {string} functions - array of standard functions
		 * @example
		 * <pre><code>
		 * OnGptPluginsOptions: function (options)
		 * {
		 * 		options.additionalInformation = "your specific instruction";
		 * 		options.signature = null; //disable signature
		 * }
		 * </code></pre>
		 */
		OnGptPluginsOptions: function (options)
		{
			//
		},
		/**
		 * @param {string} should be a group identifier
		 * @example
		 * GetGroupForAssignTo: function ()
		 *{
		 *   return "groupname@domain.com";
		 *}
		 */
		GetGroupForAssignTo: function ()
		{ },

		/**
		 * This function is called to change the maximum number of tries for a cognitive service.
		 * @param {string} service - name of the service being retried, possible values are:
		 * - 'AnalyzeSentiments' : sentiment analysis, default value is 1 (no retries)
		 * - 'Classify': classification using GPT, default value is 3
		 * - 'Extract': extraction from free text emails, default value is 3
		 * - 'GptPlugins': generation of conversation suggested reply, default value is 3
		 * - 'DocumentClassification': classification with KNN (cf SDA configuration), default value is 1 (no retries)
		 * @returns {number} - the maximum number of tries for the service (1: one try no retries) or undefined to use the default value
		 * @example
		 * getGptRetriesNumber: function (service)
		 *{
			const services = {
				AnalyzeSentiments: 1,
				Classify: 3,
				Extract: 3,
				GptPlugins: 3,
				"DocumentClassification": 1,
			};
			return services[service];
		 *}
		 */
		getGptRetriesNumber: function (service)
		{ },
		/**
		 * This function is called when a CIM (Customer Interaction Management) conversation message is received.
		 * This function can be used to execute any custom logic or processing when an email or message is received in a conversation.
		 * This function does not receive any parameters and does not return any value.
		 * @returns {void}
		 * @example
		 * <pre><code>
		 * OnCIMConversationMessageReceived: function ()
		 * {
		 *     // Send a notification
		 *     Sys.Helpers.SendEmail("admin@company.com", "New Message", "A new conversation message has been received");
		 * }
		 * </code></pre>
		 */

		OnCIMConversationMessageReceived: function ()
		{ }
	};
	return Common;
})();
